### PR TITLE
Remove most Optifine resourcepack feature alternative mods

### PR DESCRIPTION
**Pull request by HyperSoop**
Devin never got around to doing this, i suppose (?)  
I'm sorry for not knowing any other way to mass delete files other than just to delete them one by one. Also this may be broken.

### CODE REVIEW

**Comment by Gaming32** [comment]
Why do you think these need to be removed?

**Comment by osfanbuff63** [comment]
Don't really think there's any reason for this, just is going to cause me more headaches since I use OptiFine-alternative RPs...

**Comment by HyperSoop** [comment]
> Why do you think these need to be removed?

Since they are not required to join the server as well as don't provide any improvement without a resourcepack that uses them.

**Comment by Gaming32** [comment]
I could see potentially making them optional, but removing them I don't agree with.

**Comment by HyperSoop** [comment]
If this does not get the majority's approval, feel free to close this PR.

**Comment by intergrav** [comment]
Yeah, I kinda forgot to do this lmao. I do think they should be optional, but not completely removed

**Comment by jadelily18** [comment]
These definitely shouldn't be removed but making them optional is fine with me as long as most people agree.

**Comment by HyperSoop** [comment]
I should revert the deletions and just change the .toml-s to state they are optional then

**Comment by HyperSoop** [comment]
okay i have no idea how to revert those commits now

**Comment by intergrav** [comment]
just did this in https://github.com/modrinth-smp/pack/commit/1bac6b519ae13a813312b6274259f17b29d8c414

**Pull request closed without merging**
