### PR TITLE
1.19.2

### PR DESCRIPTION
**Pull request by Gaming32**
Updates to 1.19.2. Also updates pack version to 2.0.x.

## Added mods
The following mods come from my [Wild Liminal](https://modrinth.com/modpack/wild-liminal) pack, which was somewhat of a test for having them here.
+ [Wilder Wild](https://modrinth.com/mod/wilder-wild)
+ [The Corners](https://modrinth.com/mod/the-corners)
+ [Liminal Plus](https://modrinth.com/mod/liminal-plus)
+ [DimensionalDoors](https://www.curseforge.com/minecraft/mc-mods/dimensionaldoors)

## Still awaiting 1.19.2 update
+ CC:C Bridge
+ DeepslateGenerator

## Mods that are being removed
+ Create Plus (it's part of Create now)
+ Hold That Chunk (I thought it was a different mod when I added it)
+ Weapon leveling (it caused issues with Hex Casting and isn't on 1.19.2)

## Mods whose 1.19.2 update is under development
+ Gate of Babylon

### CODE REVIEW

**Review by intergrav — APPROVED** [review]
did a quick look-over, lgtm 👍🏽

**Review by kuylar — APPROVED** [review]

**Comment by Gaming32** [comment]
3

2

1

**Comment by HyperSoop** [comment]
Some mods need to be reclassified as server/client mods. I don't think i need the rep mod on the client

**Comment by Gaming32** [comment]
It affects the singleplayer server

**Comment by HyperSoop** [comment]
I'm not sure anyone will be playing singleplayer with this modpack and using server admin utilities there.

**Comment by HyperSoop** [comment]
@Gaming32 The quick connect button appears to be set to `localhost/127.0.0.1:25565`, which is definitely not the actual server.

**Comment by HyperSoop** [comment]
@Gaming32 Dimensional Doors seems to have a huge issue on startup, spitting hundreds of warns and errors while loading its assets and slowing down startup time significantly.

**Comment by Gaming32** [comment]
You could've tested this stuff when I asked everyone to test this PR.

**Comment by HyperSoop** [comment]
Only got around to that now when there's a published release and the server's soon to start. There appears to be a simular issue with The Corners, it spits out a stack trace and fails to load something on load. I'll try isolating it more though

**Comment by HyperSoop** [comment]
I'm pretty sure the pack needs quite some debloating to prevent such issues from popping up, there are many mods that barely do anything but increase complexity of the pack, making it slightly more likely to crash and perform slightly worse, and those small mods add up when you keep adding them.

**Comment by HyperSoop** [comment]
Dimensional Doors also seems like a _very_ intrusive mod, making you go to limbo every time you die. I can see this being one of the most annoying mods to have ever been added, so if you're having it, have it as the focus of the pack.

**Comment by Gaming32** [comment]
You only go to Limbo if you die in a Dimensional Doors dimension

**Pull request merged**
