### PR TITLE
Spellbound Enchantments + Ease Enchancement configuration

### PR DESCRIPTION
**Pull request by HyperSoop**
Adds Spellbound (another enchant mod); adjusts the Enchancement configuration to be less strict on which enchants are allowed. More variety!

### CODE REVIEW

**Review by intergrav — APPROVED** [review]

**Comment by jadelily18** [comment]
I'll take a look at this when my PC can connect to GitHub lmao

**Review by Gaming32 — APPROVED** [review]
Seems fine to me

**Comment by osfanbuff63** [comment]
You should be able to add this with Packwiz, so that we don't have to redistribute said mod (https://modrinth.com/mod/spellbound-enchantments) but since it's supposedly CC0 we might not to do that

**Comment by intergrav** [comment]
> You should be able to add this with Packwiz, so that we don't have to redistribute said mod (https://modrinth.com/mod/spellbound-enchantments) but since it's supposedly CC0 we might not to do that

There is no 1.18.2 version available on MR

**Comment by HyperSoop** [comment]
> > You should be able to add this with Packwiz, so that we don't have to redistribute said mod (https://modrinth.com/mod/spellbound-enchantments) but since it's supposedly CC0 we might not to do that
> 
> There is no 1.18.2 version available on MR

there might be a version on github though

**Comment by HyperSoop** [comment]
thanks for fixing my noobness, devin

**Pull request merged**
